# Generated by Django 2.0.1 on 2018-01-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='popularity_index',
            field=models.IntegerField(default=0),
        ),
    ]
